### ISSUE TITLE
[MC Version]: 1.19.2 Crashes with new Create 0.5.1 installed

### ISSUE THREAD

**Issue by ArsiTheFox** [NovaStarter/Create-Crystal-Clear#28]
Version: Forge 1.19.2 43.2.11

The Create mod has updated and this mod fails to run with it installed

- Steps to reproduce
Run Forge new Create-Crystal-Clear with new Create mod update!

LOGS: 
  `[21:49:33] [modloading-worker-0/ERROR]: Failed to create mod instance. ModID: create_crystal_clear, class com.cyvack.create_crystal_clear.Create_Crystal_Clear
java.lang.NoSuchMethodError: 'com.tterrag.registrate.util.nullness.NonNullSupplier com.simibubi.create.foundation.data.CreateRegistrate.lazy(java.lang.String)'
	at com.cyvack.create_crystal_clear.Create_Crystal_Clear.<clinit>(Create_Crystal_Clear.java:22) ~[create_crystal_clear-0.1.2e-1.19.2.jar%23316!/:1.0]
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?]
	at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499) ~[?:?]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:480) ~[?:?]
	at net.minecraftforge.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:68) ~[javafmllanguage-1.19.2-43.2.11.jar%23413!/:?]
	at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$10(ModContainer.java:121) ~[fmlcore-1.19.2-43.2.11.jar%23412!/:?]
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) [?:?]
	at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796) [?:?]
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) [?:?]
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) [?:?]
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) [?:?]
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) [?:?]
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) [?:?]`

**Comment by Cyvack** [comment]
issue has already been fixed, just not pushed https://github.com/NovaStarter/Create-Crystal-Clear/issues/26
