### ISSUE TITLE
Crash on Startup: java.lang.reflect.InvocationTargetException: null

### ISSUE THREAD

**Issue by kideroplays** [NovaStarter/Create-Crystal-Clear#33]
Oi 

Ive had some issue lately where it would just randomly crash with the newest version of kubejs create
Crashlog:
-- MOD create_crystal_clear --
Details:
	Caused by 0: java.lang.reflect.InvocationTargetException
		at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?] {}
		at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77) ~[?:?] {}
		at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?] {}
		at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499) ~[?:?] {}
		at java.lang.reflect.Constructor.newInstance(Constructor.java:480) ~[?:?] {}
		at net.minecraftforge.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:68) ~[javafmllanguage-1.19.2-43.2.21.jar%23257!/:?] {}
		at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$10(ModContainer.java:121) ~[fmlcore-1.19.2-43.2.21.jar%23256!/:?] {}
		at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) ~[?:?] {}
		at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796) ~[?:?] {}
		at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?] {}
		at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[?:?] {}
		at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[?:?] {re:computing_frames}
		at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[?:?] {re:computing_frames}
		at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[?:?] {}

	Caused by 1: java.lang.ExceptionInInitializerError
		at com.cyvack.create_crystal_clear.CrystalClear.<init>(CrystalClear.java:30) ~[create_crystal_clear-0.2.1-1.19.2.jar%23217!/:1.0] {re:classloading}
		at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?] {}
		at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77) ~[?:?] {}
		at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?] {}
		at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499) ~[?:?] {}
		at java.lang.reflect.Constructor.newInstance(Constructor.java:480) ~[?:?] {}
		at net.minecraftforge.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:68) ~[javafmllanguage-1.19.2-43.2.21.jar%23257!/:?] {}
		at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$10(ModContainer.java:121) ~[fmlcore-1.19.2-43.2.21.jar%23256!/:?] {}
		at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) ~[?:?] {}
		at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796) ~[?:?] {}
		at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?] {}
		at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[?:?] {}
		at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[?:?] {re:computing_frames}
		at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[?:?] {re:computing_frames}
		at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[?:?] {}

	Mod File: /C:/Users/my user/curseforge/minecraft/Instances/Create Modpack/mods/create_crystal_clear-0.2.1-1.19.2.jar
	Failure message: Create: Crystal Clear (create_crystal_clear) has failed to load correctly
		java.lang.reflect.InvocationTargetException: null
	Mod Version: 1.19.2-0.2.a
	Mod Issue URL: https://github.com/NovaStarter/Create-Crystal-Clear/issues
	Exception message: java.util.ConcurrentModificationException
Stacktrace:
	at java.util.HashMap.computeIfAbsent(HashMap.java:1221) ~[?:?] {re:mixin}
	at com.jozufozu.flywheel.core.StitchedSprite.<init>(StitchedSprite.java:24) ~[flywheel-forge-1.19.2-0.6.9-18.jar%23275!/:0.6.9-18] {re:classloading}
	at com.jozufozu.flywheel.core.StitchedSprite.<init>(StitchedSprite.java:28) ~[flywheel-forge-1.19.2-0.6.9-18.jar%23275!/:0.6.9-18] {re:classloading}
	at com.simibubi.create.foundation.block.render.SpriteShiftEntry.set(SpriteShiftEntry.java:13) ~[create-1.19.2-0.5.1.c.jar%23214!/:0.5.1.c] {re:classloading}
	at com.simibubi.create.foundation.block.connected.CTSpriteShifter.lambda$getCT$0(CTSpriteShifter.java:22) ~[create-1.19.2-0.5.1.c.jar%23214!/:0.5.1.c] {re:classloading}
	at net.minecraftforge.fml.DistExecutor.unsafeRunWhenOn(DistExecutor.java:111) ~[fmlcore-1.19.2-43.2.21.jar%23256!/:?] {}
	at com.simibubi.create.foundation.block.connected.CTSpriteShifter.getCT(CTSpriteShifter.java:22) ~[create-1.19.2-0.5.1.c.jar%23214!/:0.5.1.c] {re:classloading}
	at com.cyvack.create_crystal_clear.index.CCSpriteShifts.getCT(CCSpriteShifts.java:28) ~[create_crystal_clear-0.2.1-1.19.2.jar%23217!/:1.0] {re:classloading}
	at com.cyvack.create_crystal_clear.index.CCSpriteShifts.getCT(CCSpriteShifts.java:32) ~[create_crystal_clear-0.2.1-1.19.2.jar%23217!/:1.0] {re:classloading}
	at com.cyvack.create_crystal_clear.index.CCSpriteShifts.omni(CCSpriteShifts.java:14) ~[create_crystal_clear-0.2.1-1.19.2.jar%23217!/:1.0] {re:classloading}
	at com.cyvack.create_crystal_clear.data_gen.BlockBuilders.glassCasing(BlockBuilders.java:73) ~[create_crystal_clear-0.2.1-1.19.2.jar%23217!/:1.0] {re:classloading}
	at com.cyvack.create_crystal_clear.index.CCBlocks.lambda$static$0(CCBlocks.java:16) ~[create_crystal_clear-0.2.1-1.19.2.jar%23217!/:1.0] {re:classloading}
	at com.cyvack.create_crystal_clear.index.GlassBlockList.<init>(GlassBlockList.java:24) ~[create_crystal_clear-0.2.1-1.19.2.jar%23217!/:1.0] {re:classloading}
	at com.cyvack.create_crystal_clear.index.CCBlocks.<clinit>(CCBlocks.java:16) ~[create_crystal_clear-0.2.1-1.19.2.jar%23217!/:1.0] {re:classloading}
	at com.cyvack.create_crystal_clear.CrystalClear.<init>(CrystalClear.java:30) ~[create_crystal_clear-0.2.1-1.19.2.jar%23217!/:1.0] {re:classloading}
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77) ~[?:?] {}
	at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?] {}
	at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499) ~[?:?] {}
	at java.lang.reflect.Constructor.newInstance(Constructor.java:480) ~[?:?] {}
	at net.minecraftforge.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:68) ~[javafmllanguage-1.19.2-43.2.21.jar%23257!/:?] {}
	at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$10(ModContainer.java:121) ~[fmlcore-1.19.2-43.2.21.jar%23256!/:?] {}
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) ~[?:?] {}
	at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796) ~[?:?] {}
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[?:?] {re:computing_frames}
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[?:?] {re:computing_frames}
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[?:?] {}

**Comment by FoxyFox909** [comment]
Hi, I seem to be having a very similar issue.

I am on **1.18.2, using Create 0.5.1c with the latest version of Crystal Clear (Crystal Clear 0.2.1).**
I am also running the latest **KubeJS Create** (kubejs-create-forge-1802.2.4-build.5).

Logs look very similar to the OP:  https://gist.github.com/FoxyFox909/8215dd2f562f34da6e68187001548a96

![image](https://github.com/NovaStarter/Create-Crystal-Clear/assets/110856509/41eb6eb5-c7d3-46d0-b92e-9e8ab7f69677)

**Comment by FoxyFox909** [comment]
Upon further research, the issue might be on Create's end, possibly: https://github.com/Creators-of-Create/Create/issues/5121

Upon even more testing, other add-ons also seem to be having trouble with Create, Unsure how much of it is the add-ons vs create not working with each other.
