### ISSUE TITLE
1.18.2 Server Startup NPE

### ISSUE THREAD

**Issue by FoxyFox909** [NovaStarter/Create-Crystal-Clear#34]
I'm on the latest version of Crystal Clear, Forge 40.2.10, running Create 0.5.1c. I keep getting a NullPointerException from Crystal Clear when trying to start my modpack's server.

```
[02Aug2023 12:09:22.590] [modloading-worker-0/INFO] [com.tterrag.registrate.AbstractRegistrate/]: Detected new forge version, registering events reflectively.
[02Aug2023 12:09:28.263] [main/INFO] [com.floofappreciationclub.vulpinian_skies_core.VulpinianSkiesCore/]: HELLO from Register Block
[02Aug2023 12:09:29.876] [main/INFO] [com.chrisgli.gemsnjewels.Main/]: HELLO from Register Block
[02Aug2023 12:09:31.333] [main/ERROR] [net.minecraftforge.fml.javafmlmod.FMLModContainer/]: Exception caught during firing event: Registry entry not present: create:shaft
	Index: 3
	Listeners:
		0: NORMAL
		1: ASM: com.tterrag.registrate.AbstractRegistrate$1EventProxy@12dd4f20 onRegister(Lnet/minecraftforge/event/RegistryEvent$Register;)V
		2: LOWEST
		3: ASM: com.tterrag.registrate.AbstractRegistrate$1EventProxy@12dd4f20 onRegisterLate(Lnet/minecraftforge/event/RegistryEvent$Register;)V
java.lang.NullPointerException: Registry entry not present: create:shaft
	at java.base/java.util.Objects.requireNonNull(Objects.java:334)
	at TRANSFORMER/Registrate.MC1._18._2@1.1.3/com.tterrag.registrate.util.entry.RegistryEntry.get(RegistryEntry.java:91)
	at TRANSFORMER/Registrate.MC1._18._2@1.1.3/com.tterrag.registrate.util.entry.RegistryEntry.get(RegistryEntry.java:28)
	at TRANSFORMER/create@0.5.1.c/com.simibubi.create.content.decoration.encasing.EncasingRegistry.lambda$addVariantTo$1(EncasingRegistry.java:32)
	at TRANSFORMER/Registrate.MC1._18._2@1.1.3/com.tterrag.registrate.builders.Builder.lambda$onRegisterAfter$1(Builder.java:182)
	at java.base/java.lang.Iterable.forEach(Iterable.java:75)
	at TRANSFORMER/Registrate.MC1._18._2@1.1.3/com.tterrag.registrate.AbstractRegistrate.onRegisterLate(AbstractRegistrate.java:290)
	at TRANSFORMER/Registrate.MC1._18._2@1.1.3/com.tterrag.registrate.AbstractRegistrate$1EventProxy.onRegisterLate(AbstractRegistrate.java:222)
	at net.minecraftforge.eventbus.ASMEventHandler_70_1EventProxy_onRegisterLate_Register.invoke(.dynamic)
	at MC-BOOTSTRAP/eventbus@5.0.3/net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85)
	at MC-BOOTSTRAP/eventbus@5.0.3/net.minecraftforge.eventbus.EventBus.post(EventBus.java:302)
	at MC-BOOTSTRAP/eventbus@5.0.3/net.minecraftforge.eventbus.EventBus.post(EventBus.java:283)
	at LAYER PLUGIN/javafmllanguage@1.18.2-40.2.10/net.minecraftforge.fml.javafmlmod.FMLModContainer.acceptEvent(FMLModContainer.java:106)
	at LAYER PLUGIN/fmlcore@1.18.2-40.2.10/net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$4(ModContainer.java:107)
	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804)
	at LAYER PLUGIN/fmlcore@1.18.2-40.2.10/net.minecraftforge.fml.ModWorkManager$SyncExecutor.driveOne(ModWorkManager.java:42)
	at LAYER PLUGIN/fmlcore@1.18.2-40.2.10/net.minecraftforge.fml.ModWorkManager$DrivenExecutor.drive(ModWorkManager.java:26)
	at LAYER PLUGIN/fmlcore@1.18.2-40.2.10/net.minecraftforge.fml.ModLoader.waitForTransition(ModLoader.java:202)
	at LAYER PLUGIN/fmlcore@1.18.2-40.2.10/net.minecraftforge.fml.ModLoader.lambda$dispatchAndHandleError$21(ModLoader.java:187)
	at java.base/java.util.Optional.ifPresent(Optional.java:178)
	at LAYER PLUGIN/fmlcore@1.18.2-40.2.10/net.minecraftforge.fml.ModLoader.dispatchAndHandleError(ModLoader.java:187)
	at LAYER PLUGIN/fmlcore@1.18.2-40.2.10/net.minecraftforge.fml.ModLoader.lambda$gatherAndInitializeMods$11(ModLoader.java:164)
	at java.base/java.lang.Iterable.forEach(Iterable.java:75)
	at LAYER PLUGIN/fmlcore@1.18.2-40.2.10/net.minecraftforge.fml.ModLoader.gatherAndInitializeMods(ModLoader.java:164)
	at TRANSFORMER/forge@40.2.10/net.minecraftforge.server.loading.ServerModLoader.load(ServerModLoader.java:32)
	at TRANSFORMER/minecraft@1.18.2/net.minecraft.server.Main.main(Main.java:112)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at MC-BOOTSTRAP/fmlloader@1.18.2-40.2.10/net.minecraftforge.fml.loading.targets.CommonServerLaunchHandler.lambda$launchService$0(CommonServerLaunchHandler.java:32)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@9.1.3/cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@9.1.3/cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@9.1.3/cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@9.1.3/cpw.mods.modlauncher.Launcher.run(Launcher.java:106)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@9.1.3/cpw.mods.modlauncher.Launcher.main(Launcher.java:77)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@9.1.3/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@9.1.3/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23)
	at cpw.mods.bootstraplauncher@1.0.0/cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:149)

[02Aug2023 12:09:31.334] [main/ERROR] [net.minecraftforge.fml.javafmlmod.FMLModContainer/LOADING]: Caught exception during event RegistryEvent.Register<minecraft:block> dispatch for modid create_crystal_clear
java.lang.NullPointerException: Registry entry not present: create:shaft
	at java.util.Objects.requireNonNull(Objects.java:334) ~[?:?]
	at com.tterrag.registrate.util.entry.RegistryEntry.get(RegistryEntry.java:91) ~[Registrate-MC1.18.2-1.1.3.jar%23271!/:?]
	at com.tterrag.registrate.util.entry.RegistryEntry.get(RegistryEntry.java:28) ~[Registrate-MC1.18.2-1.1.3.jar%23271!/:?]
	at com.simibubi.create.content.decoration.encasing.EncasingRegistry.lambda$addVariantTo$1(EncasingRegistry.java:32) ~[create-1.18.2-0.5.1.c.jar%2381!/:0.5.1.c]
	at com.tterrag.registrate.builders.Builder.lambda$onRegisterAfter$1(Builder.java:182) ~[Registrate-MC1.18.2-1.1.3.jar%23271!/:?]
	at java.lang.Iterable.forEach(Iterable.java:75) ~[?:?]
	at com.tterrag.registrate.AbstractRegistrate.onRegisterLate(AbstractRegistrate.java:290) ~[Registrate-MC1.18.2-1.1.3.jar%23271!/:?]
	at com.tterrag.registrate.AbstractRegistrate$1EventProxy.onRegisterLate(AbstractRegistrate.java:222) ~[Registrate-MC1.18.2-1.1.3.jar%23271!/:?]
	at net.minecraftforge.eventbus.ASMEventHandler_70_1EventProxy_onRegisterLate_Register.invoke(.dynamic) ~[?:?]
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85) ~[eventbus-5.0.3.jar%232!/:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-5.0.3.jar%232!/:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-5.0.3.jar%232!/:?]
	at net.minecraftforge.fml.javafmlmod.FMLModContainer.acceptEvent(FMLModContainer.java:106) ~[javafmllanguage-1.18.2-40.2.10.jar%23221!/:?]
	at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$4(ModContainer.java:107) ~[fmlcore-1.18.2-40.2.10.jar%23220!/:?]
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) ~[?:?]
	at net.minecraftforge.fml.ModWorkManager$SyncExecutor.driveOne(ModWorkManager.java:42) ~[fmlcore-1.18.2-40.2.10.jar%23220!/:?]
	at net.minecraftforge.fml.ModWorkManager$DrivenExecutor.drive(ModWorkManager.java:26) ~[fmlcore-1.18.2-40.2.10.jar%23220!/:?]
	at net.minecraftforge.fml.ModLoader.waitForTransition(ModLoader.java:202) ~[fmlcore-1.18.2-40.2.10.jar%23220!/:?]
	at net.minecraftforge.fml.ModLoader.lambda$dispatchAndHandleError$21(ModLoader.java:187) ~[fmlcore-1.18.2-40.2.10.jar%23220!/:?]
	at java.util.Optional.ifPresent(Optional.java:178) ~[?:?]
	at net.minecraftforge.fml.ModLoader.dispatchAndHandleError(ModLoader.java:187) ~[fmlcore-1.18.2-40.2.10.jar%23220!/:?]
	at net.minecraftforge.fml.ModLoader.lambda$gatherAndInitializeMods$11(ModLoader.java:164) ~[fmlcore-1.18.2-40.2.10.jar%23220!/:?]
	at java.lang.Iterable.forEach(Iterable.java:75) ~[?:?]
	at net.minecraftforge.fml.ModLoader.gatherAndInitializeMods(ModLoader.java:164) ~[fmlcore-1.18.2-40.2.10.jar%23220!/:?]
	at net.minecraftforge.server.loading.ServerModLoader.load(ServerModLoader.java:32) ~[forge-1.18.2-40.2.10-universal.jar%23224!/:?]
	at net.minecraft.server.Main.main(Main.java:112) ~[server-1.18.2-20220404.173914-srg.jar%23219!/:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at net.minecraftforge.fml.loading.targets.CommonServerLaunchHandler.lambda$launchService$0(CommonServerLaunchHandler.java:32) ~[fmlloader-1.18.2-40.2.10.jar%2318!/:?]
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-9.1.3.jar%235!/:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) [modlauncher-9.1.3.jar%235!/:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) [modlauncher-9.1.3.jar%235!/:?]
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:106) [modlauncher-9.1.3.jar%235!/:?]
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:77) [modlauncher-9.1.3.jar%235!/:?]
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) [modlauncher-9.1.3.jar%235!/:?]
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) [modlauncher-9.1.3.jar%235!/:?]
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:149) [bootstraplauncher-1.0.0.jar:?]
```
[full latest.log](https://github.com/NovaStarter/Create-Crystal-Clear/files/12243556/crystal_latest.log)

I have also seen it get a NPE with a cogwheel:

```
[02Aug2023 12:26:39.120] [main/ERROR] [net.minecraft.server.Main/FATAL]: Failed to start the minecraft server
net.minecraftforge.fml.LoadingFailedException: Loading errors encountered: [
	Create: Crystal Clear (create_crystal_clear) encountered an error during the common_setup event phase
§7java.lang.NullPointerException: Registry entry not present: create:large_cogwheel
]
	at net.minecraftforge.fml.ModLoader.waitForTransition(ModLoader.java:222) ~[fmlcore-1.18.2-40.2.10.jar%23220!/:?]
	at net.minecraftforge.fml.ModLoader.lambda$dispatchAndHandleError$21(ModLoader.java:187) ~[fmlcore-1.18.2-40.2.10.jar%23220!/:?]
	at java.util.Optional.ifPresent(Optional.java:178) ~[?:?]
	at net.minecraftforge.fml.ModLoader.dispatchAndHandleError(ModLoader.java:187) ~[fmlcore-1.18.2-40.2.10.jar%23220!/:?]
	at net.minecraftforge.fml.ModLoader.lambda$gatherAndInitializeMods$11(ModLoader.java:164) ~[fmlcore-1.18.2-40.2.10.jar%23220!/:?]
	at java.lang.Iterable.forEach(Iterable.java:75) ~[?:?]
	at net.minecraftforge.fml.ModLoader.gatherAndInitializeMods(ModLoader.java:164) ~[fmlcore-1.18.2-40.2.10.jar%23220!/:?]
	at net.minecraftforge.server.loading.ServerModLoader.load(ServerModLoader.java:32) ~[forge-1.18.2-40.2.10-universal.jar%23224!/:?]
	at net.minecraft.server.Main.main(Main.java:112) ~[server-1.18.2-20220404.173914-srg.jar%23219!/:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at net.minecraftforge.fml.loading.targets.CommonServerLaunchHandler.lambda$launchService$0(CommonServerLaunchHandler.java:32) ~[fmlloader-1.18.2-40.2.10.jar%2318!/:?]
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-9.1.3.jar%235!/:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) [modlauncher-9.1.3.jar%235!/:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) [modlauncher-9.1.3.jar%235!/:?]
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:106) [modlauncher-9.1.3.jar%235!/:?]
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:77) [modlauncher-9.1.3.jar%235!/:?]
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) [modlauncher-9.1.3.jar%235!/:?]
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) [modlauncher-9.1.3.jar%235!/:?]
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:149) [bootstraplauncher-1.0.0.jar:?]
```

[crystal_cogwheel_npe_latest.log](https://github.com/NovaStarter/Create-Crystal-Clear/files/12243570/crystal_cogwheel_npe_latest.log)

**Comment by FoxyFox909** [comment]
I think the mod just needs to update to support 0.5.1c ^^

I'll be waiting patiently. This is a great little mod and I wanna add it in my modpack! But I can't downgrade Create, sadly.
