### ISSUE TITLE
Parsing error loading recipe create_crystal_clear:steel_glass_casing

### ISSUE THREAD

**Issue by MarbleGateKeeper** [NovaStarter/Create-Crystal-Clear#9]
it leaves below info in console:
```
[2911月2022 23:04:36.386] [Worker-Main-3/ERROR] [net.minecraft.world.item.crafting.RecipeManager/]: Parsing error loading recipe create_crystal_clear:steel_glass_casing
com.google.gson.JsonSyntaxException: Unknown item 'alloyed:steel_ingot'
	at net.minecraft.world.item.crafting.ShapedRecipe.m_151280_(ShapedRecipe.java:276) ~[server-1.18.2-20220404.173914-srg.jar%23107!/:?]
	at java.util.Optional.orElseThrow(Optional.java:403) ~[?:?]
	at net.minecraft.world.item.crafting.ShapedRecipe.m_151278_(ShapedRecipe.java:275) ~[server-1.18.2-20220404.173914-srg.jar%23107!/:?]
	at net.minecraft.world.item.crafting.Ingredient.m_43919_(Ingredient.java:222) ~[server-1.18.2-20220404.173914-srg.jar%23107!/:?]
	at net.minecraftforge.common.crafting.VanillaIngredientSerializer.parse(VanillaIngredientSerializer.java:27) ~[forge-1.18.2-40.1.80-universal.jar%23112!/:?]
	at net.minecraftforge.common.crafting.CraftingHelper.getIngredient(CraftingHelper.java:143) ~[forge-1.18.2-40.1.80-universal.jar%23112!/:?]
	at net.minecraft.world.item.crafting.Ingredient.m_43917_(Ingredient.java:197) ~[server-1.18.2-20220404.173914-srg.jar%23107!/:?]
	at ......
```
I believe you should use
```
"conditions": [
    {
      "type": "forge:mod_loaded",
      "modid": "alloyed"
    }
  ],
```
in your recipe.

**Comment by Cyvack** [comment]
Ah, thank you. I didn't realize a conditional statement for recipes existed. I'll make sure to add that when I get the time.
